/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const CultivationCultivationIdLazyImport = createFileRoute(
  '/cultivation/$cultivationId',
)()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const CultivationCultivationIdLazyRoute =
  CultivationCultivationIdLazyImport.update({
    path: '/cultivation/$cultivationId',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/cultivation.$cultivationId.lazy').then((d) => d.Route),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/cultivation/$cultivationId': {
      id: '/cultivation/$cultivationId'
      path: '/cultivation/$cultivationId'
      fullPath: '/cultivation/$cultivationId'
      preLoaderRoute: typeof CultivationCultivationIdLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  CultivationCultivationIdLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/cultivation/$cultivationId"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/cultivation/$cultivationId": {
      "filePath": "cultivation.$cultivationId.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
